### ISSUE TITLE
Utiliser un fichier JSON (le convertir en tableau ?)

### ISSUE THREAD

**Issue by benjaminguyomarch** [m2dimi/Noctilus#6]
Bonsoir, 

Nous avons réussit avec votre adresse à calculter la distance entre deux coordonnées (dont l'une qui est tapé dans le champs de recherche). Nous arrivons à effectuer ce calcul, lorsque les coordonnées sont sous formes de tableau dans le code.

Cependant, nous n'arrivons pas à utiliser les coordonnées avec le fichier json (bddlatlng.json) :
var points=(data=('bddlatlng.json'));
var radial_distance = d3.geo.distance([maLat,maLong], [points[1].lat, points[1].lon]);

**Comment by danieleguido** [comment]
Salut Benjamin,

le code que tu as écrit n'est pas vraiment du javascript ... ;-)
D'abord, il faut charger d3 avant son utilisation, sinon il n'y a pas de
d3.geo. Le calcul de la distance doit etre fait une fois les données
collectées, precisement à l'interieur de la fonction start (script.js,
ligne 61).
Une fois que la variable data est *bien remplie*, comme tu peux voir dans
la console javascript - où les erreurs aussi sont affichés:

var distances = [];
for( var i in data) {

}

**Comment by danieleguido** [comment]
Salut Benjamin,

D'abord, il faut charger d3 avant son utilisation, sinon il n'y a pas de
d3.geo. Le calcul de la distance doit etre fait une fois les données
collectées, precisement à l'interieur de la fonction start (script.js,
ligne 61).
Une fois que la variable data est _bien remplie_, comme tu peux voir dans
la console javascript - où les erreurs aussi sont affichés:

``` javascript
var distances = [];
for( var i in data) {
   distances.push({
     dist: d3.geo.distance([maLat,maLong], [data[i].lat, data[i].lon]),
     place: data[i]
   });
}

console.log(distances)
// sort distances, cfr https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/sort

// takes the first 5 points, usling slice, cfr https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/slice
```
